# /usr/local/bin/docker-compose -f /docs/dev-ops/environment/environment-docker-compose.yml up -d
version: '3.8'
# docker-compose -f environment-docker-compose.yml up -d
services:
  chatgpt-data-app:
    image: halfhalf/chatgpt-data-app:1.1
    container_name: chatgpt-data-app
    ports:
      - "8080:8080"
    environment:
      - TZ=PRC
      - SERVER_PORT=8080
      - APP_CONFIG_API_VERSION=v1
      - APP_CONFIG_CROSS_ORIGIN=*
      - THREAD_POOL_EXECUTOR_CONFIG_CORE_POOL_SIZE=20
      - THREAD_POOL_EXECUTOR_CONFIG_MAX_POOL_SIZE=50
      - THREAD_POOL_EXECUTOR_CONFIG_KEEP_ALIVE_TIME=5000
      - THREAD_POOL_EXECUTOR_CONFIG_BLOCK_QUEUE_SIZE=5000
      - THREAD_POOL_EXECUTOR_CONFIG_POLICY=CallerRunsPolicy
      - CHATGPT_SDK_CONFIG_API_HOST=https://api.openai.com/
      - CHATGPT_SDK_CONFIG_API_KEY=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
      - WX_CONFIG_ORIGINALID=gh_921349cd1dd5
      - WX_CONFIG_APPID=wx42655b60199b097a
      - WX_CONFIG_TOKEN=b8b6

    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  chatgpt-web:
    container_name: chatgpt-web
    image: halfhalf/chatgpt-web:1.0
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_HOST_URL=http://localhost:8080
    restart: always
