server:
  port: 8080

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # 访问频次限制
    limit-count: 1
    # 白名单，不做频次拦截【微信的openai】oxfA9w8-23yvwTmo2ombz0E4zJv4
    white-list: ojbZUv18lbmriaTjcCWBYkOrSbHA,oqeYL6Wuch96ISoXz7N-cxr0vmJQ

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      api-host: https://api.openai.com/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: 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
      # 自主申请 http://api.xfg.im:8080/authorize?username=xfg&password=123 - 有时效性，主要为了大家学习使用
      auth-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4ZmciLCJleHAiOjE2OTAwMzI5MDQsImlhdCI6MTY5MDAyOTMwNCwianRpIjoiOTBkNzc5NjYtOWM5MS00MGVmLWJmNjktNzYzNDljNmUyMDkyIiwidXNlcm5hbWUiOiJ4ZmcifQ.x7P6Rc249SgbxpqWhgKahYP8A8AllNI_26DV08a1AZs
wx:
  config:
    originalid: gh_921349cd1dd5
    appid: wx42655b60199b097a
    token: b8b6
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml